//
// Generated file, do not edit! Created by nedtool 5.0 from DL_PDU.msg.
//

#ifndef __DL_PDU_M_H
#define __DL_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>DL_PDU.msg:20</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * packet DL_PDU
 * {
 *     int id;
 *     string type;
 *     int source;
 *     int destination;
 * }
 * </pre>
 */
class DL_PDU : public ::omnetpp::cPacket
{
  protected:
    int id;
    ::omnetpp::opp_string type;
    int source;
    int destination;

  private:
    void copy(const DL_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const DL_PDU&);

  public:
    DL_PDU(const char *name=nullptr, int kind=0);
    DL_PDU(const DL_PDU& other);
    virtual ~DL_PDU();
    DL_PDU& operator=(const DL_PDU& other);
    virtual DL_PDU *dup() const {return new DL_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getId() const;
    virtual void setId(int id);
    virtual const char * getType() const;
    virtual void setType(const char * type);
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const DL_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, DL_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __DL_PDU_M_H

