//
// Generated file, do not edit! Created by nedtool 5.0 from A_PDU.msg.
//

#ifndef __A_PDU_M_H
#define __A_PDU_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0500
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Enum generated from <tt>A_PDU.msg:19</tt> by nedtool.
 * <pre>
 * //
 * // TODO generated message class
 * //
 * enum Type
 * {
 * 
 *     DATA = 0;
 *     ACK = 1;
 * }
 * </pre>
 */
enum Type {
    DATA = 0,
    ACK = 1
};

/**
 * Class generated from <tt>A_PDU.msg:20</tt> by nedtool.
 * <pre>
 * packet A_PDU
 * {
 *     int mId;
 *     char alphabet;
 *     int type @enum(Type);
 * }
 * </pre>
 */
class A_PDU : public ::omnetpp::cPacket
{
  protected:
    int mId;
    char alphabet;
    int type;

  private:
    void copy(const A_PDU& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const A_PDU&);

  public:
    A_PDU(const char *name=nullptr, int kind=0);
    A_PDU(const A_PDU& other);
    virtual ~A_PDU();
    A_PDU& operator=(const A_PDU& other);
    virtual A_PDU *dup() const {return new A_PDU(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b);

    // field getter/setter methods
    virtual int getMId() const;
    virtual void setMId(int mId);
    virtual char getAlphabet() const;
    virtual void setAlphabet(char alphabet);
    virtual int getType() const;
    virtual void setType(int type);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const A_PDU& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, A_PDU& obj) {obj.parsimUnpack(b);}


#endif // ifndef __A_PDU_M_H

